export const INCREMENT = "INCREMENT";
export const DECREMENT = "DECREMENT";
export const PRODUCT_LIST ="PRODUCT_LIST";
export const PRODUCT_LIST_FETCHING ="PRODUCT_LIST_FETCHING";
export const PRODUCT_LIST_SUCCESS = "PRODUCT_LIST_SUCCESS";
export const ADD_TO_CART = "ADD_TO_CART";
export const DELETE_FROM_CART = "DELETE_FROM_CART ";
export const FILTER_PRODUCTS ="FILTER_PRODUCTS";
